---
title: "A descriptive analysis of road traffic collisions pre- and post-20mph speed zone expansion in Edinburgh and Glasgow"
output: html_notebook
author: Torran Semple
date: 17/03/2025
---



```{r, warning=FALSE}

### Plot & grid arrangements to compare AADF in Edinburgh & Glasgow

# Load combined Edinburgh & Glasgow data
ED_GLA <- read.csv("/Users/psxts6/Desktop/20mph/EDA_Traffic_Accidents_dStats_Visuals/ED_GLA_accidents_traffic_summary.csv", header = TRUE, sep = ",")

library(ggplot2)

# All
a1 <- ggplot(ED_GLA, aes(x = year, y = annual_avg)) + 
  geom_line(aes(color = city, group = city), size = 0.5, linetype = "dashed") + 
  geom_point(color = "black", size = 2, shape = 16) +
  labs(x="Year", y="AADF", color="City") +
  ggtitle("AADF: All Modes") + 
  theme_bw() +
  theme(text = element_text(family="Arial", size = 17), 
                            axis.text.x = element_text(angle=45, hjust=1)) + 
  scale_y_continuous(breaks= seq(0, 30000, 3000), limits=c(0, 30000)) + 
  scale_x_continuous(breaks = seq(2010, 2022, by = 1))


# Cars
a2 <- ggplot(ED_GLA, aes(x = year, y = car_avg_year)) + 
  geom_line(aes(color = city, group = city), size = 0.5, linetype = "dashed") + 
  geom_point(color = "black", size = 2, shape = 16) + 
  labs(x="Year", y="AADF", color="City") + 
  ggtitle("AADF: Cars") + 
  theme_bw() +
  theme(text = element_text(family="Arial", size = 17), 
                            axis.text.x = element_text(angle=45, hjust=1)) + 
  scale_y_continuous(breaks= seq(0, 25000, 2500), limits=c(0, 25000)) + 
  scale_x_continuous(breaks = seq(2010, 2022, by = 1))


# Buses  
a3 <- ggplot(ED_GLA, aes(x = year, y = bus_avg_year)) + 
  geom_line(aes(color = city, group = city), size = 0.5, linetype = "dashed") + 
  geom_point(color = "black", size = 2, shape = 16) +
  labs(x="Year", y="AADF", color="City") + 
  ggtitle("AADF: Buses") + 
  theme_bw() +
  theme(text = element_text(family="Arial", size = 17), 
                            axis.text.x = element_text(angle=45, hjust=1)) + 
  scale_y_continuous(breaks= seq(0, 600, 75), limits=c(0, 600)) + 
  scale_x_continuous(breaks = seq(2010, 2022, by = 1))


# Cycles
a4 <- ggplot(ED_GLA, aes(x = year, y = cycle_avg_year)) + 
  geom_line(aes(color = city, group = city), size = 0.5, linetype = "dashed") + 
  geom_point(color = "black", size = 2, shape = 16) + 
  labs(x="Year", y="AADF", color="City") +
  ggtitle("AADF: Cycles") + 
  theme_bw() +
  theme(text = element_text(family="Arial", size = 17), 
                            axis.text.x = element_text(angle=45, hjust=1)) + 
  scale_y_continuous(breaks= seq(0, 200, 20), limits=c(0, 200)) + 
  scale_x_continuous(breaks = seq(2010, 2022, by = 1))




# Grid for AADF per mode
library(cowplot)
gridx <- plot_grid(a1,a2,a3,a4, nrow = 2, align = "g")
gridx


```


```{r, warning=FALSE}

### Arrangement to compare KSIs (absolute and as % OF ACCIDENTS) in Edinburgh & Glasgow


# Frequency of KSIs
k1 <- ggplot(ED_GLA, aes(x = year, y = ksi_count)) + 
  geom_line(aes(color = city, group = city), size = 0.5, linetype = "dashed") + 
  geom_point(color = "black", size = 2, shape = 16) + 
  labs(x="Year", y="Frequency", color="City") + 
  ggtitle("KSI Frequency (all RTCs)") + 
  theme_bw() +
  theme(text = element_text(family="Arial", size = 17), 
                            axis.text.x = element_text(angle=45, hjust=1)) + 
  scale_y_continuous(breaks= seq(0, 250, 25), limits=c(0, 250)) + 
  scale_x_continuous(breaks = seq(2010, 2022, by = 1))


# % KSI
k2 <- ggplot(ED_GLA, aes(x = year, y = ksi_prop)) + 
  geom_line(aes(color = city, group = city), size = 0.5, linetype = "dashed") + 
  geom_point(color = "black", size = 2, shape = 16) + 
  labs(x="Year", y="KSI % of RTCs", color="City") + 
  ggtitle("Proportion Resulting in KSI (all RTCs)") + 
  theme_bw() +
  theme(text = element_text(family="Arial", size = 17), 
                            axis.text.x = element_text(angle=45, hjust=1)) + 
  scale_y_continuous(breaks= seq(0, 40, 5), limits=c(0, 40)) + 
  scale_x_continuous(breaks = seq(2010, 2022, by = 1))
 


```


```{r, warning=FALSE}

### Arrangement to compare annual rate of accidents (per 100,000 vehicles, i.e., 'accidents_annual_rate') in Edinburgh and Glasgow

# (SS) Note, to do this we have to first generate a new column in the ED_GLA df: number_accidents/annual_avg
# (SS) Create new column for number of accidents divided by AADF
# (SS) new_column_name <- "accidents_over_aadf"
# (SS) Create the new column with division
# (SS) ED_GLA <- ED_GLA %>% mutate({{ new_column_name }} := number_accidents / annual_avg)


# Number of accidents/annual AADF
z1 <- ggplot(ED_GLA, aes(x = year, y = accidents_annual_rate)) + 
  geom_line(aes(color = city, group = city), size = 0.5, linetype = "dashed") +
  geom_point(color = "black", size = 2, shape = 16) + 
  labs(x="Year", y="RTC Frequency/Annual AADF", color="City") + 
  ggtitle("RTC Rate per 100,000 Vehicles") + 
  theme_bw() +
  theme(text = element_text(family="Arial", size = 17), 
                            axis.text.x = element_text(angle=45, hjust=1)) + 
  scale_y_continuous(breaks= seq(0, 18, 2), limits=c(0, 18)) + 
  scale_x_continuous(breaks = seq(2010, 2022, by = 1))

# Explanation: Seems that as soon as 20mph zones are introduced and expanded, accidents (as a proportion of traffic volume) decrease quite predictably year-on-year; Also a big jump from 2018 to 2019, mirroring what we see in the KSI graphs; could this mean (as I think we discussed before), 20mph zones seem to lead in a significant decrease *in number of accidents per year* but the number of KSIs remains constant, hence the %KSIs is much higher than previous years

# Further note: The way that the Edinburgh and Glasgow trends mirror each other so closely in this plot is definitely worth discussion, particularly as the 20mph approach was quite different in both cities, i.e., there may be other factors dictating this trend


```


```{r, warning=FALSE}

### Arrangement to compare annual rate of KSIs (per 100,000 vehicles) in Edinburgh & Glasgow

# Frequency of KSIs/annual AADF
z2 <- ggplot(ED_GLA, aes(x = year, y = ksi_annual_rate)) + 
  geom_line(aes(color = city, group = city), size = 0.5, linetype = "dashed") +
  geom_point(color = "black", size = 2, shape = 16) + 
  labs(x="Year", y="KSI Frequency/Annual AADF", color="City") + 
  ggtitle("KSI Rate per 100,000 Vehicles") + 
  theme_bw() +
  theme(text = element_text(family="Arial", size = 17), 
                            axis.text.x = element_text(angle=45, hjust=1)) + 
  scale_y_continuous(breaks= seq(0, 3, 0.3), limits=c(0, 3)) + 
  scale_x_continuous(breaks = seq(2010, 2022, by = 1))
z2

# Grid for RTC rate and KSI rate (all RTCs only - comparable with traffic data)
gridy <- plot_grid(z1, z2, nrow = 1, align = "g")
gridy

```




```{r}

### Arrangement to compare fatal collisions (absolute and as % OF ACCIDENTS) in Edinburgh & Glasgow


# Frequency of fatalities
f1 <- ggplot(ED_GLA, aes(x = year, y = fatal_count)) + 
  geom_line(aes(color = city, group = city), size = 0.5, linetype = "dashed") + 
  geom_point(color = "black", size = 2, shape = 16) + 
  labs(x="Year", y="Frequency", color="City") + 
  ggtitle("Frequency of Fatal Collisions") + 
  theme_bw() +
  theme(text = element_text(family="Arial", size = 17), 
                            axis.text.x = element_text(angle=45, hjust=1)) + 
  scale_y_continuous(breaks= seq(0, 16, 2), limits=c(0, 16)) + 
  scale_x_continuous(breaks = seq(2010, 2022, by = 1))



# % of fatalities
f2 <- ggplot(ED_GLA, aes(x = year, y = fatal_prop)) + 
   geom_line(aes(color = city, group = city), size = 0.5, linetype = "dashed") + 
   geom_point(color = "black", size = 2, shape = 16) + 
   labs(x="Year", y="Fatality % of RTCs", color="City") + 
   ggtitle("Proportion of Fatal Collisions") + 
   theme_bw() +
   theme(text = element_text(family="Arial", size = 17), 
                            axis.text.x = element_text(angle=45, hjust=1)) + 
   scale_y_continuous(breaks= seq(0, 2.5, 0.25), limits=c(0, 2.5)) + 
   scale_x_continuous(breaks = seq(2010, 2022, by = 1))


# grid.arrange(k1,k2,f1,f2, ncol=2) 


```


```{r, warning=FALSE}

### Arrangement to compare SV KSIs on LOW SPEED roads (absolute and as %) in Edinburgh & Glasgow

# Load combined LOW SPEED Edinburgh & Glasgow data
ED_GLA_LS <- read.csv("/Users/psxts6/Desktop/20mph/EDA_Traffic_Accidents_dStats_Visuals/ED_GLA_LOW_SPEED_SV_accidents_traffic_summary.csv", header = TRUE, sep = ",")


# Frequency of KSIs
k3 <- ggplot(ED_GLA_LS, aes(x = year, y = ksi_count_LS)) + 
  geom_line(aes(color = city, group = city), size = 0.5, linetype = "dashed") + 
  geom_point(color = "black", size = 2, shape = 16) + 
  labs(x="Year", y="Frequency", color="City") + 
  ggtitle("KSI Frequency (single-vehicle, low-speed RTCs)") + 
  theme_bw() +
  theme(text = element_text(family="Arial", size = 17), 
                            axis.text.x = element_text(angle=45, hjust=1)) + 
  scale_y_continuous(breaks= seq(0, 150, 15), limits=c(0, 150)) +
  scale_x_continuous(breaks = seq(2010, 2022, by = 1))
  


# % KSI
k4 <- ggplot(ED_GLA_LS, aes(x = year, y = ksi_prop_LS)) + 
  geom_line(aes(color = city, group = city), size = 0.5, linetype = "dashed") + 
  geom_point(color = "black", size = 2, shape = 16) + 
  labs(x="Year", y="KSI % of RTCs", color="City") + 
  ggtitle("Proportion Resulting in KSI (single-vehicle, low-speed RTCs)") + 
  theme_bw() +
  theme(text = element_text(family="Arial", size = 17), 
                            axis.text.x = element_text(angle=45, hjust=1)) + 
  scale_y_continuous(breaks= seq(0, 50, 5), limits=c(0, 50)) +
  scale_x_continuous(breaks = seq(2010, 2022, by = 1))


# All KSI plots: all RTCs vs SV LS RTCs
gridz <- plot_grid(k1,k2,k3,k4, nrow = 2, align = "g")
gridz

```



```{r}

### (Same as above) arrangement to compare SV LS fatal collisions (absolute and as %) in Edinburgh & Glasgow


# Frequency of fatalities
f3 <- ggplot(ED_GLA_LS, aes(x = year, y = fatal_count_LS)) + 
  geom_line(aes(color = city, group = city), size = 0.5, linetype = "dashed") + 
  geom_point(color = "black", size = 1.5, shape = 16) + 
  labs(x="Year", y="Frequency", color="City") + 
  ggtitle("Frequency of SV Fatal Collisions on 20/30mph roads") +
  theme_bw() +
  theme(text = element_text(family="Arial", size = 17), 
                            axis.text.x = element_text(angle=45, hjust=1)) + 
  scale_y_continuous(breaks= seq(0, 12, 2), limits=c(0, 12)) +
  scale_x_continuous(breaks = seq(2010, 2022, by = 1))

  

scale_y_continuous(breaks= seq(0, 12, 2), limits=c(0, 12)) +

# % of fatalities
f4 <- ggplot(ED_GLA_LS, aes(x = year, y = fatal_prop_LS)) + 
  geom_line(aes(color = city, group = city), size = 0.5, linetype = "dashed") +
  geom_point(color = "black", size = 1.5, shape = 16) +
  labs(x="Year", y="Fatality % of RTCs", color="City") +
  ggtitle("Proportion of SV Fatal Collisions on 20/30mph roads") + 
  theme_bw() +
  theme(text = element_text(family="Arial", size = 17), 
                            axis.text.x = element_text(angle=45, hjust=1)) + 
  scale_y_continuous(breaks= seq(0, 3.5, 0.5), limits=c(0, 3.5)) +
  scale_x_continuous(breaks = seq(2010, 2022, by = 1))


# note: 'library(cowplot)' is an alternative to 'gridExtra' if package is buggy
# gridx <- plot_grid(k3,k4,f3,f4, nrow = 2, align = "g")
# gridx

# grid.arrange(k3,k4,f3,f4, nrow = 2)
# for 2*2 KSI & fatality grid


```


```{r, warning=FALSE}

### New arrangement to compare absolute RTCs in Edinburgh and Glasgow (all & LS roads)


# Absolute RTCs (all roads)
n1 <- ggplot(ED_GLA, aes(x = year, y = number_accidents)) + 
  geom_line(aes(color = city, group = city), size = 0.5, linetype = "dashed") + 
  geom_point(color = "black", size = 2, shape = 16) + 
  labs(x="Year", y="Frequency", color="City") + 
  ggtitle("RTC Frequency (all RTCs)") + 
  theme_bw() +
  theme(text = element_text(family="Arial", size = 17), 
                            axis.text.x = element_text(angle=45, hjust=1)) + 
  scale_y_continuous(breaks= seq(0, 1400, 100), limits=c(0, 1400)) +
  scale_x_continuous(breaks = seq(2010, 2022, by = 1))


# Absolute RTCs (20/30mph roads)
n2 <- ggplot(ED_GLA_LS, aes(x = year, y = number_accidents_LS)) + 
  geom_line(aes(color = city, group = city), size = 0.5, linetype = "dashed") +
  geom_point(color = "black", size = 2, shape = 16) + 
  labs(x="Year", y="Frequency", color="City") + 
  ggtitle("RTC Frequency (single-vehicle, low-speed RTCs)") + 
  theme_bw() +
  theme(text = element_text(family="Arial", size = 17), 
                            axis.text.x = element_text(angle=45, hjust=1)) + 
  scale_y_continuous(breaks= seq(0, 500, 50), limits=c(0, 500)) +
  scale_x_continuous(breaks = seq(2010, 2022, by = 1))

n2

grida <- plot_grid(n1,n2, nrow = 1, align = "g")
grida

```


```{r}

### Additional miscellaneous d-stats

# ED pre vs post pedestrian KSIs

# pre 20mph
library(sqldf)
ED_pre_ped <- sqldf("SELECT * 
FROM ED_SV_PRE
WHERE casualty_type_cas1_pedestrian = 1")
table(ED_pre_ped$ksi)

# post 20mph
ED_post_ped <- sqldf("SELECT * 
FROM ED_SV_POST
WHERE casualty_type_cas1_pedestrian = 1")
table(ED_post_ped$ksi)



# GLA pre vs post pedestrian KSIs

# pre 20mph
GLA_pre_ped <- sqldf("SELECT * 
FROM GLA_SV_PRE
WHERE casualty_type_cas1_pedestrian = 1")
table(GLA_pre_ped$ksi)

# post 20mph
GLA_post_ped <- sqldf("SELECT * 
FROM GLA_SV_POST
WHERE casualty_type_cas1_pedestrian = 1")
table(GLA_post_ped$ksi)





# Same as above for other road users

# ED pre vs post other KSIs

# pre 20mph
library(sqldf)
ED_pre_other <- sqldf("SELECT * 
FROM ED_SV_PRE
WHERE casualty_type_cas1_pedestrian = 0")
table(ED_pre_other$ksi)

# post 20mph
ED_post_other <- sqldf("SELECT * 
FROM ED_SV_POST
WHERE casualty_type_cas1_pedestrian = 0")
table(ED_post_other$ksi)



# GLA pre vs post other KSIs

# pre 20mph
GLA_pre_other <- sqldf("SELECT * 
FROM GLA_SV_PRE
WHERE casualty_type_cas1_pedestrian = 0")
table(GLA_pre_other$ksi)

# post 20mph
GLA_post_other <- sqldf("SELECT * 
FROM GLA_SV_POST
WHERE casualty_type_cas1_pedestrian = 0")
table(GLA_post_other$ksi)




```


```{r}

### Same as above repeated for fatalities

# ED pre vs post pedestrian fatal

# pre 20mph
table(ED_pre_ped$fatal)

# post 20mph
table(ED_post_ped$fatal)



# GLA pre vs post pedestrian fatal

# pre 20mph
table(GLA_pre_ped$fatal)

# post 20mph
table(GLA_post_ped$fatal)




# Same as above for other road users

# ED pre vs post other fatal

# pre 20mph
table(ED_pre_other$fatal)

# post 20mph
table(ED_post_other$fatal)



# GLA pre vs post other fatal

# pre 20mph
table(GLA_pre_other$fatal)

# post 20mph
table(GLA_post_other$fatal)



```





